### ISSUE TITLE
Feature request: use mix() helper instead

### ISSUE THREAD

**Issue by drmzio** [Rebel59/oc-mix-manifest-plugin#1]
The `getVersionedCss` doesn't make sense when using JavaScript. Could this be updated?

**Comment by web-studio-51** [comment]
An exception has been thrown during the rendering of a template ("file_get_contents(): Filename cannot be empty").
![image](https://user-images.githubusercontent.com/44437378/50053642-9ffe6300-0149-11e9-9f8a-0d09bd81ba43.png)
help plz)

**Comment by CptMeatball** [comment]
@web-studio-51 can you post this as a separate issue please.

**Comment by CptMeatball** [comment]
@drmzio will look into this! Seems like a good change!

**Comment by CptMeatball** [comment]
@drmzio Totally forgot about this one. Currently have a local build that supports "mix". Will update soon ;)

**Comment by CptMeatball** [comment]
Fixed by https://github.com/Rebel59/oc-mix-manifest-plugin/commit/f329e25519785e2eac634b03eb1f961c7ed060db
